server:
  port: 8081
command-center:
  actions:
    mode: SIMULATED
spring:
  mongodb:
    database: christopherbell
    uri: mongodb://localhost:27017
  data:
    mongodb:
      auto-index-creation: true
