server:
  port: 8080
spring:
  mongodb:
    database: christopherbell
    uri: mongodb://localhost:27017
  data:
    mongodb:
      auto-index-creation: true
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt:
    secret: ${APP_JWT_SECRET:}
  mail:
    from: ${APP_MAIL_FROM:noreply@christopherbell.dev}
command-center:
  enabled: true
  log-path: C:/ProgramData/christopherbell.dev/logs/ChristopherBellDev.out.log
  actions:
    mode: WINDOWS
    power-actions-enabled: ${COMMAND_CENTER_POWER_ACTIONS_ENABLED:false}
    win-sw-executable: C:/ProgramData/christopherbell.dev/service/ChristopherBellDev.exe
    shutdown-executable: C:/Windows/System32/shutdown.exe
    power-delay: 60s
