name: CI Build

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: [ 25 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Set BUILD_NUMBER env
        if: runner.os != 'Windows'
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set BUILD_NUMBER env on Windows
        if: runner.os == 'Windows'
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $env:GITHUB_ENV

      - name: Grant execute permission for Gradle
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build and Test
        if: runner.os != 'Windows'
        run: ./gradlew build

      - name: Build and Test on Windows
        if: runner.os == 'Windows'
        run: .\gradlew.bat build
